In [72]:
cartela=[[]]

In [79]:
import random

In [81]:
from random import randint

In [6]:
cartela

[[]]

In [7]:
import numpy as np

In [8]:
np.array

<function numpy.core.multiarray.array>

In [10]:
cartela = np.array((5,5))

In [11]:
cartela

array([5, 5])

In [12]:
np.zeros((4,4), dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
cartela = np.zeros((5,5), dtype=np.float64)

In [84]:
cartela

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
cartela[0,0] = random.randint(1, 15)
cartela[1,0] = random.randint(1, 15)
while(cartela[1,0]==cartela[0,0]):
    cartela[1,0] = random.randint(1, 15)
    
cartela[2,0] = random.randint(1, 15)

while(cartela[2,0]==cartela[0,0] or cartela[2,0]==cartela[1,0]):
    cartela[2,0] = random.randint(1, 15)
    
cartela[3,0] = random.randint(1, 15)

while(cartela[3,0]==cartela[0,0] or cartela[3,0]==cartela[1,0] or cartela[3,0]==cartela[2,0]):
    cartela[3,0] = random.randint(1, 15)

cartela[4,0] = random.randint(1, 15)

while(cartela[4,0]==cartela[0,0] or cartela[4,0]==cartela[1,0] or cartela[4,0]==cartela[2,0] or cartela[4,0]==cartela[3,0]):
    cartela[4,0] = random.randint(1, 15)
    

In [86]:
cartela

array([[ 4.,  0.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.],
       [13.,  0.,  0.,  0.,  0.],
       [ 5.,  0.,  0.,  0.,  0.]])

In [87]:
cartela[0,1] = random.randint(16, 30)
cartela[1,1] = random.randint(16, 30)
while(cartela[1,1]==cartela[0,1]):
    cartela[1,1] = random.randint(16, 30)
    
cartela[2,1] = random.randint(16, 30)

while(cartela[2,1]==cartela[0,1] or cartela[2,1]==cartela[1,1]):
    cartela[2,1] = random.randint(16, 30)
    
cartela[3,1] = random.randint(16, 30)

while(cartela[3,1]==cartela[0,1] or cartela[3,1]==cartela[1,1] or cartela[3,1]==cartela[2,1]):
    cartela[3,1] = random.randint(16, 30)

cartela[4,1] = random.randint(16, 30)

while(cartela[4,1]==cartela[0,1] or cartela[4,1]==cartela[1,1] or cartela[4,1]==cartela[2,1] or cartela[4,1]==cartela[3,1]):
    cartela[4,1] = random.randint(16, 30)

In [88]:
cartela

array([[ 4., 29.,  0.,  0.,  0.],
       [ 8., 27.,  0.,  0.,  0.],
       [ 3., 21.,  0.,  0.,  0.],
       [13., 22.,  0.,  0.,  0.],
       [ 5., 28.,  0.,  0.,  0.]])

In [97]:
cartela[0,2] = random.randint(31, 45)
cartela[1,2] = random.randint(31, 45)
while(cartela[1,2]==cartela[0,2]):
    cartela[1,2] = random.randint(31, 45)
    
cartela[2,2] = 0
    
cartela[3,2] = random.randint(31, 45)

while(cartela[3,2]==cartela[0,2] or cartela[3,2]==cartela[1,2] or cartela[3,2]==cartela[2,2]):
    cartela[3,2] = random.randint(31, 45)

cartela[4,2] = random.randint(31, 45)

while(cartela[4,2]==cartela[0,2] or cartela[4,2]==cartela[1,2] or cartela[4,2]==cartela[2,2] or cartela[4,2]==cartela[3,2]):
    cartela[4,2] = random.randint(31, 45)

In [98]:
cartela

array([[ 4., 29., 44.,  0.,  0.],
       [ 8., 27., 36.,  0.,  0.],
       [ 3., 21.,  0.,  0.,  0.],
       [13., 22., 35.,  0.,  0.],
       [ 5., 28., 43.,  0.,  0.]])

In [102]:
cartela[0,3] = random.randint(46, 60)
cartela[1,3] = random.randint(46, 60)
while(cartela[1,3]==cartela[0,3]):
    cartela[1,3] = random.randint(46, 60)
    
cartela[2,3] = random.randint(46, 60)

while(cartela[2,3]==cartela[0,3] or cartela[2,3]==cartela[1,3]):
    cartela[2,3] = random.randint(46, 60)
    
cartela[3,3] = random.randint(46, 60)
while(cartela[3,3]==cartela[0,3] or cartela[3,3]==cartela[1,3] or cartela[3,3]==cartela[2,3]):
    cartela[3,3] = random.randint(46, 60)

cartela[4,3] = random.randint(46, 60)

while(cartela[4,3]==cartela[0,3] or cartela[4,3]==cartela[1,3] or cartela[4,3]==cartela[2,3] or cartela[4,3]==cartela[3,3]):
    cartela[4,3] = random.randint(46, 60)

In [103]:
cartela

array([[ 4., 29., 44., 60.,  0.],
       [ 8., 27., 36., 50.,  0.],
       [ 3., 21.,  0., 52.,  0.],
       [13., 22., 35., 47.,  0.],
       [ 5., 28., 43., 57.,  0.]])

In [106]:
cartela[0,4] = random.randint(61, 75)
cartela[1,4] = random.randint(61, 75)
while(cartela[1,4]==cartela[0,4]):
    cartela[1,4] = random.randint(61, 75)
    
cartela[2,4] = random.randint(61, 75)

while(cartela[2,4]==cartela[0,4] or cartela[2,4]==cartela[1,4]):
    cartela[2,4] = random.randint(61, 75)
    
cartela[3,4] = random.randint(61, 75)
while(cartela[3,4]==cartela[0,4] or cartela[3,4]==cartela[1,4] or cartela[3,4]==cartela[2,4]):
    cartela[3,4] = random.randint(61, 75)

cartela[4,4] = random.randint(61, 75)
while(cartela[4,4]==cartela[0,4] or cartela[4,4]==cartela[1,4] or cartela[4,4]==cartela[2,4] or cartela[4,4]==cartela[3,4]):
    cartela[4,4] = random.randint(61, 75)

In [107]:
cartela

array([[ 4., 29., 44., 60., 68.],
       [ 8., 27., 36., 50., 69.],
       [ 3., 21.,  0., 52., 74.],
       [13., 22., 35., 47., 70.],
       [ 5., 28., 43., 57., 73.]])

In [119]:
def cartelaBingo():
    import random
    import numpy as np
    cartela = np.zeros((5,5), dtype=np.float64)
    
    
        #gerando valores 1 coluna
    
    cartela[0,0] = random.randint(1, 15)
    cartela[1,0] = random.randint(1, 15)
    while(cartela[1,0]==cartela[0,0]):
        cartela[1,0] = random.randint(1, 15)
    
    cartela[2,0] = random.randint(1, 15)
    while(cartela[2,0]==cartela[0,0] or cartela[2,0]==cartela[1,0]):
        cartela[2,0] = random.randint(1, 15)

    cartela[3,0] = random.randint(1, 15)
    while(cartela[3,0]==cartela[0,0] or cartela[3,0]==cartela[1,0] or cartela[3,0]==cartela[2,0]):
        cartela[3,0] = random.randint(1, 15)

    cartela[4,0] = random.randint(1, 15)
    while(cartela[4,0]==cartela[0,0] or cartela[4,0]==cartela[1,0] or cartela[4,0]==cartela[2,0] or cartela[4,0]==cartela[3,0]):
        cartela[4,0] = random.randint(1, 15)

        #gerando valores 2 coluna
        
    cartela[0,1] = random.randint(16, 30)
    cartela[1,1] = random.randint(16, 30)
    while(cartela[1,1]==cartela[0,1]):
        cartela[1,1] = random.randint(16, 30)

    cartela[2,1] = random.randint(16, 30)

    while(cartela[2,1]==cartela[0,1] or cartela[2,1]==cartela[1,1]):
        cartela[2,1] = random.randint(16, 30)

    cartela[3,1] = random.randint(16, 30)

    while(cartela[3,1]==cartela[0,1] or cartela[3,1]==cartela[1,1] or cartela[3,1]==cartela[2,1]):
        cartela[3,1] = random.randint(16, 30)

    cartela[4,1] = random.randint(16, 30)

    while(cartela[4,1]==cartela[0,1] or cartela[4,1]==cartela[1,1] or cartela[4,1]==cartela[2,1] or cartela[4,1]==cartela[3,1]):
        cartela[4,1] = random.randint(16, 30)       
        
    
        #gerando valores 3 coluna

    cartela[0,2] = random.randint(31, 45)
    cartela[1,2] = random.randint(31, 45)
    while(cartela[1,2]==cartela[0,2]):
        cartela[1,2] = random.randint(31, 45)

    cartela[2,2] = 0
    
    cartela[3,2] = random.randint(31, 45)
    while(cartela[3,2]==cartela[0,2] or cartela[3,2]==cartela[1,2] or cartela[3,2]==cartela[2,2]):
        cartela[3,2] = random.randint(31, 45)

    cartela[4,2] = random.randint(31, 45)
    while(cartela[4,2]==cartela[0,2] or cartela[4,2]==cartela[1,2] or cartela[4,2]==cartela[2,2] or cartela[4,2]==cartela[3,2]):
        cartela[4,2] = random.randint(31, 45)
        
        
        #gerando valores 4 coluna

    cartela[0,3] = random.randint(46, 60)
    cartela[1,3] = random.randint(46, 60)
    while(cartela[1,3]==cartela[0,3]):
        cartela[1,3] = random.randint(46, 60)

    cartela[2,3] = random.randint(46, 60)

    while(cartela[2,3]==cartela[0,3] or cartela[2,3]==cartela[1,3]):
        cartela[2,3] = random.randint(46, 60)

    cartela[3,3] = random.randint(46, 60)
    while(cartela[3,3]==cartela[0,3] or cartela[3,3]==cartela[1,3] or cartela[3,3]==cartela[2,3]):
        cartela[3,3] = random.randint(46, 60)

    cartela[4,3] = random.randint(46, 60)

    while(cartela[4,3]==cartela[0,3] or cartela[4,3]==cartela[1,3] or cartela[4,3]==cartela[2,3] or cartela[4,3]==cartela[3,3]):
        cartela[4,3] = random.randint(46, 60)
    
    
        #gerando valores 5 coluna

    cartela[0,4] = random.randint(61, 75)
    cartela[1,4] = random.randint(61, 75)
    while(cartela[1,4]==cartela[0,4]):
        cartela[1,4] = random.randint(61, 75)

    cartela[2,4] = random.randint(61, 75)

    while(cartela[2,4]==cartela[0,4] or cartela[2,4]==cartela[1,4]):
        cartela[2,4] = random.randint(61, 75)

    cartela[3,4] = random.randint(61, 75)
    while(cartela[3,4]==cartela[0,4] or cartela[3,4]==cartela[1,4] or cartela[3,4]==cartela[2,4]):
        cartela[3,4] = random.randint(61, 75)

    cartela[4,4] = random.randint(61, 75)
    while(cartela[4,4]==cartela[0,4] or cartela[4,4]==cartela[1,4] or cartela[4,4]==cartela[2,4] or cartela[4,4]==cartela[3,4]):
        cartela[4,4] = random.randint(61, 75)
        
    print(cartela)

In [131]:
cartelaBingo()

[[ 1. 16. 44. 55. 75.]
 [ 6. 30. 40. 46. 69.]
 [ 4. 28.  0. 47. 64.]
 [13. 27. 45. 56. 63.]
 [10. 26. 41. 60. 67.]]
